apiVersion: v1
kind: ReplicationController
metadata:
    name: mimicchio-replica
spec:
    replicas: 2
    selector: 
        app: mimicchio
    template:
        metadata:
            labels:
                app: mimicchio
        spec:
            containers:
                - name: k8s-mimicchio
                  image: mts88/sample1
                  ports:
                    - containerPort: 3000
